[package]
name = "puzzle_2025_17"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
fxhash = "0.2.1"
itertools = "0.14.0"

[lints]
workspace = true
