[package]
name = "puzzle_2025_18"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
once_cell = "1.21.3"
regex = "1.11.3"

[lints]
workspace = true
